---
aws_bucket: www.crystalforrubyists.com
skip_regex: (pdf)|(mobi)|(epub)|(md)|(book/header.html)|(book/footer.html)|(txt)|(yml)|(Makefile)|(gitignore)|(xml)|(.tgz)|(LICENSE)$ |(.crystal)|(.DS_Store)
